function [S_textscan_table] = llegir_dades(txt_data_name, write_values, separador_char, variable_names)

% Llegeix i guarda en una taula (S_textscan_table) l'arxiu de text "main_data_analysis.txt"
% Funció de la app 'app_selection_pannel'.
% NOTA: El nombre màxim d'elements és 10 (ampliable)
%
% Variables
% write_values : és el codi del fprint que s'ha d'entrar.
%           ex2: "%f%s%s%f%f%f%f%f%f%f%f%f%f%s%s%s%s%s%s%s%s%f"
% separador_char: separador que tindràn els valors de cada cell
%           ex: "$"
% txt_data_name : directori i nom del arxiu.
%           ex: "Results\main_results_josep.txt"
% variable_names : nom de les variables en la taula
%           ex:  ["IsCeleg","NomWorm", "Length", "Bounding", "Modifs", "Indx_skel", "Indx_BW", "WidthValues"]
% 
%
% % Exemple: 
% [S_textscan_table] = llegir_dades("Taula_Josep.txt", tipologia_formatspec_table(app.S_textscan_tracking), "$", app.S_textscan_tracking.Properties.VariableNames);
%
% See also
% write_dades_cell
% app_interf_guardar_main_dades
% app_interf_descriure_dades


% START FUNCTION


% _Obtenim la lectura_
fid = fopen(txt_data_name);
S_textscan = textscan(fid, write_values, 'Delimiter', separador_char); % Elapsed time is 0.000535 seconds.
fclose(fid);

% _Mirem el nombre d'elements_
% segons el codi d'entrada
[~, matches_split] = strsplit(write_values, "%");
num_col = numel(matches_split);

% disp("Num columnes llegir_dades")
% num_col

% Ho passem a taula
if num_col == 1
    S_textscan_table = table(string(S_textscan{1}), ...
                            'VariableNames', variable_names);
elseif num_col == 2
    S_textscan_table = table(string(S_textscan{1}), ...
                              string(S_textscan{2}), ...
                            'VariableNames', variable_names);
elseif num_col == 3
    S_textscan_table = table(string(S_textscan{1}), ...
                              string(S_textscan{2}), ...
                              string(S_textscan{3}), ...
                            'VariableNames', variable_names);
elseif num_col == 4
    S_textscan_table = table(string(S_textscan{1}), ...
                              string(S_textscan{2}), ...
                              string(S_textscan{3}), ...
                              string(S_textscan{4}), ...
                            'VariableNames', variable_names);
elseif num_col == 5
    S_textscan_table = table(string(S_textscan{1}), ...
                              string(S_textscan{2}), ...
                              string(S_textscan{3}), ...
                              string(S_textscan{4}), ...
                              string(S_textscan{5}), ...
                            'VariableNames', variable_names);
elseif num_col == 6
    S_textscan_table = table(string(S_textscan{1}), ...
                              string(S_textscan{2}), ...
                              string(S_textscan{3}), ...
                              string(S_textscan{4}), ...
                              string(S_textscan{5}), ...
                              string(S_textscan{6}), ...
                            'VariableNames', variable_names);
elseif num_col == 7
    S_textscan_table = table(string(S_textscan{1}), ...
                              string(S_textscan{2}), ...
                              string(S_textscan{3}), ...
                              string(S_textscan{4}), ...
                              string(S_textscan{5}), ...
                              string(S_textscan{6}), ...
                              string(S_textscan{7}), ...
                            'VariableNames', variable_names);
elseif num_col == 8
    S_textscan_table = table(string(S_textscan{1}), ...
                              string(S_textscan{2}), ...
                              string(S_textscan{3}), ...
                              string(S_textscan{4}), ...
                              string(S_textscan{5}), ...
                              string(S_textscan{6}), ...
                              string(S_textscan{7}), ...
                              string(S_textscan{8}), ...
                            'VariableNames', variable_names);
elseif num_col == 9
    S_textscan_table = table(string(S_textscan{1}), ...
                              string(S_textscan{2}), ...
                              string(S_textscan{3}), ...
                              string(S_textscan{4}), ...
                              string(S_textscan{5}), ...
                              string(S_textscan{6}), ...
                              string(S_textscan{7}), ...
                              string(S_textscan{8}), ...
                              string(S_textscan{9}), ...                              
                            'VariableNames', variable_names);
elseif num_col == 10
    S_textscan_table = table(string(S_textscan{1}), ...
                              string(S_textscan{2}), ...
                              string(S_textscan{3}), ...
                              string(S_textscan{4}), ...
                              string(S_textscan{5}), ...
                              string(S_textscan{6}), ...
                              string(S_textscan{7}), ...
                              string(S_textscan{8}), ...
                              string(S_textscan{9}), ...
                              string(S_textscan{10}), ...                              
                            'VariableNames', variable_names);

elseif num_col == 11
S_textscan_table = table(string(S_textscan{1}), ...
                          string(S_textscan{2}), ...
                          string(S_textscan{3}), ...
                          string(S_textscan{4}), ...
                          string(S_textscan{5}), ...
                          string(S_textscan{6}), ...
                          string(S_textscan{7}), ...
                          string(S_textscan{8}), ...
                          string(S_textscan{9}), ...
                          string(S_textscan{10}), ...    
                          string(S_textscan{11}), ...                              
                        'VariableNames', variable_names);

elseif num_col == 12
S_textscan_table = table(string(S_textscan{1}), ...
                          string(S_textscan{2}), ...
                          string(S_textscan{3}), ...
                          string(S_textscan{4}), ...
                          string(S_textscan{5}), ...
                          string(S_textscan{6}), ...
                          string(S_textscan{7}), ...
                          string(S_textscan{8}), ...
                          string(S_textscan{9}), ...
                          string(S_textscan{10}), ...    
                          string(S_textscan{11}), ...                              
                          string(S_textscan{12}), ...                                                        
                        'VariableNames', variable_names);

elseif num_col == 13
S_textscan_table = table(string(S_textscan{1}), ...
                          string(S_textscan{2}), ...
                          string(S_textscan{3}), ...
                          string(S_textscan{4}), ...
                          string(S_textscan{5}), ...
                          string(S_textscan{6}), ...
                          string(S_textscan{7}), ...
                          string(S_textscan{8}), ...
                          string(S_textscan{9}), ...
                          string(S_textscan{10}), ...    
                          string(S_textscan{11}), ...                              
                          string(S_textscan{12}), ...          
                          string(S_textscan{13}), ...                                    
                        'VariableNames', variable_names);

elseif num_col == 14
S_textscan_table = table(string(S_textscan{1}), ...
                          string(S_textscan{2}), ...
                          string(S_textscan{3}), ...
                          string(S_textscan{4}), ...
                          string(S_textscan{5}), ...
                          string(S_textscan{6}), ...
                          string(S_textscan{7}), ...
                          string(S_textscan{8}), ...
                          string(S_textscan{9}), ...
                          string(S_textscan{10}), ...    
                          string(S_textscan{11}), ...                              
                          string(S_textscan{12}), ...          
                          string(S_textscan{13}), ...                                    
                          string(S_textscan{14}), ...                                                              
                        'VariableNames', variable_names);

elseif num_col == 15
S_textscan_table = table(string(S_textscan{1}), ...
                          string(S_textscan{2}), ...
                          string(S_textscan{3}), ...
                          string(S_textscan{4}), ...
                          string(S_textscan{5}), ...
                          string(S_textscan{6}), ...
                          string(S_textscan{7}), ...
                          string(S_textscan{8}), ...
                          string(S_textscan{9}), ...
                          string(S_textscan{10}), ...    
                          string(S_textscan{11}), ...                              
                          string(S_textscan{12}), ...          
                          string(S_textscan{13}), ...                                    
                          string(S_textscan{14}), ...                                    
                          string(S_textscan{15}), ...                                                             
                        'VariableNames', variable_names);

elseif num_col == 16
S_textscan_table = table(string(S_textscan{1}), ...
                          string(S_textscan{2}), ...
                          string(S_textscan{3}), ...
                          string(S_textscan{4}), ...
                          string(S_textscan{5}), ...
                          string(S_textscan{6}), ...
                          string(S_textscan{7}), ...
                          string(S_textscan{8}), ...
                          string(S_textscan{9}), ...
                          string(S_textscan{10}), ...    
                          string(S_textscan{11}), ...                              
                          string(S_textscan{12}), ...          
                          string(S_textscan{13}), ...                                    
                          string(S_textscan{14}), ...                                    
                          string(S_textscan{15}), ...  
                          string(S_textscan{16}), ...                            
                        'VariableNames', variable_names);
elseif num_col == 17
S_textscan_table = table(string(S_textscan{1}), ...
                          string(S_textscan{2}), ...
                          string(S_textscan{3}), ...
                          string(S_textscan{4}), ...
                          string(S_textscan{5}), ...
                          string(S_textscan{6}), ...
                          string(S_textscan{7}), ...
                          string(S_textscan{8}), ...
                          string(S_textscan{9}), ...
                          string(S_textscan{10}), ...    
                          string(S_textscan{11}), ...                              
                          string(S_textscan{12}), ...          
                          string(S_textscan{13}), ...                                    
                          string(S_textscan{14}), ...                                    
                          string(S_textscan{15}), ...  
                          string(S_textscan{16}), ...                            
                          string(S_textscan{17}), ...                                                      
                        'VariableNames', variable_names);

elseif num_col == 18
S_textscan_table = table(string(S_textscan{1}), ...
                          string(S_textscan{2}), ...
                          string(S_textscan{3}), ...
                          string(S_textscan{4}), ...
                          string(S_textscan{5}), ...
                          string(S_textscan{6}), ...
                          string(S_textscan{7}), ...
                          string(S_textscan{8}), ...
                          string(S_textscan{9}), ...
                          string(S_textscan{10}), ...    
                          string(S_textscan{11}), ...                              
                          string(S_textscan{12}), ...          
                          string(S_textscan{13}), ...                                    
                          string(S_textscan{14}), ...                                    
                          string(S_textscan{15}), ...  
                          string(S_textscan{16}), ...                            
                          string(S_textscan{17}), ...       
                          string(S_textscan{18}), ...                                
                        'VariableNames', variable_names);
elseif num_col == 19
S_textscan_table = table(string(S_textscan{1}), ...
                          string(S_textscan{2}), ...
                          string(S_textscan{3}), ...
                          string(S_textscan{4}), ...
                          string(S_textscan{5}), ...
                          string(S_textscan{6}), ...
                          string(S_textscan{7}), ...
                          string(S_textscan{8}), ...
                          string(S_textscan{9}), ...
                          string(S_textscan{10}), ...    
                          string(S_textscan{11}), ...                              
                          string(S_textscan{12}), ...          
                          string(S_textscan{13}), ...                                    
                          string(S_textscan{14}), ...                                    
                          string(S_textscan{15}), ...  
                          string(S_textscan{16}), ...                            
                          string(S_textscan{17}), ...       
                          string(S_textscan{18}), ...                                
                          string(S_textscan{19}), ...                                                          
                        'VariableNames', variable_names);

elseif num_col == 20
S_textscan_table = table(string(S_textscan{1}), ...
                          string(S_textscan{2}), ...
                          string(S_textscan{3}), ...
                          string(S_textscan{4}), ...
                          string(S_textscan{5}), ...
                          string(S_textscan{6}), ...
                          string(S_textscan{7}), ...
                          string(S_textscan{8}), ...
                          string(S_textscan{9}), ...
                          string(S_textscan{10}), ...    
                          string(S_textscan{11}), ...                              
                          string(S_textscan{12}), ...          
                          string(S_textscan{13}), ...                                    
                          string(S_textscan{14}), ...                                    
                          string(S_textscan{15}), ...  
                          string(S_textscan{16}), ...                            
                          string(S_textscan{17}), ...       
                          string(S_textscan{18}), ...                                
                          string(S_textscan{19}), ...                                                          
                          string(S_textscan{20}), ...                                                                                    
                        'VariableNames', variable_names);
elseif num_col == 21
S_textscan_table = table(string(S_textscan{1}), ...
                          string(S_textscan{2}), ...
                          string(S_textscan{3}), ...
                          string(S_textscan{4}), ...
                          string(S_textscan{5}), ...
                          string(S_textscan{6}), ...
                          string(S_textscan{7}), ...
                          string(S_textscan{8}), ...
                          string(S_textscan{9}), ...
                          string(S_textscan{10}), ...    
                          string(S_textscan{11}), ...                              
                          string(S_textscan{12}), ...          
                          string(S_textscan{13}), ...                                    
                          string(S_textscan{14}), ...                                    
                          string(S_textscan{15}), ...  
                          string(S_textscan{16}), ...                            
                          string(S_textscan{17}), ...       
                          string(S_textscan{18}), ...                                
                          string(S_textscan{19}), ...                                                          
                          string(S_textscan{20}), ...     
                          string(S_textscan{21}), ...                          
                        'VariableNames', variable_names);

elseif num_col == 22
S_textscan_table = table(string(S_textscan{1}), ...
                          string(S_textscan{2}), ...
                          string(S_textscan{3}), ...
                          string(S_textscan{4}), ...
                          string(S_textscan{5}), ...
                          string(S_textscan{6}), ...
                          string(S_textscan{7}), ...
                          string(S_textscan{8}), ...
                          string(S_textscan{9}), ...
                          string(S_textscan{10}), ...    
                          string(S_textscan{11}), ...                              
                          string(S_textscan{12}), ...          
                          string(S_textscan{13}), ...                                    
                          string(S_textscan{14}), ...                                    
                          string(S_textscan{15}), ...  
                          string(S_textscan{16}), ...                            
                          string(S_textscan{17}), ...       
                          string(S_textscan{18}), ...                                
                          string(S_textscan{19}), ...                                                          
                          string(S_textscan{20}), ...     
                          string(S_textscan{21}), ...       
                          string(S_textscan{22}), ...                                 
                        'VariableNames', variable_names);

elseif num_col == 23
S_textscan_table = table(string(S_textscan{1}), ...
                          string(S_textscan{2}), ...
                          string(S_textscan{3}), ...
                          string(S_textscan{4}), ...
                          string(S_textscan{5}), ...
                          string(S_textscan{6}), ...
                          string(S_textscan{7}), ...
                          string(S_textscan{8}), ...
                          string(S_textscan{9}), ...
                          string(S_textscan{10}), ...    
                          string(S_textscan{11}), ...                              
                          string(S_textscan{12}), ...          
                          string(S_textscan{13}), ...                                    
                          string(S_textscan{14}), ...                                    
                          string(S_textscan{15}), ...  
                          string(S_textscan{16}), ...                            
                          string(S_textscan{17}), ...       
                          string(S_textscan{18}), ...                                
                          string(S_textscan{19}), ...                                                          
                          string(S_textscan{20}), ...     
                          string(S_textscan{21}), ...       
                          string(S_textscan{22}), ...    
                          string(S_textscan{23}), ...                              
                        'VariableNames', variable_names);

end


% END FUNCTION


end