function [S_textscan_table] = read_data(txt_data_name, write_values, separador_char, variable_names)

% Read and save the text file "main_data_analysis.txt" in a table (S_textscan_table)
% Function of the app 'app_selection_pannel'.
% NOTE: The maximum number of elements is 10 (expandable)
%
% Variables
% write_values ​​: is the fprint code that must be entered.
%           ex2: "%f%s%s%f%f%f%f%f%f%f%f%f%f%s%s%s%s%s%s%s%s%f"
% separador_char: separator that will have the values ​​of each cell
%           ex: "$"
% txt_data_name : directory and name of the file.
%           ex: "Results\main_results_josep.txt"
% variable_names : name of the variables in the table
%           ex:  ["IsCeleg","NomWorm", "Length", "Bounding", "Modifs", "Indx_skel", "Indx_BW", "WidthValues"]
% 
%
% % Example: 
% [S_textscan_table] = read_data("Taula_Josep.txt", typology_formatspec_table_norm(app.S_textscan_tracking), "$", app.S_textscan_tracking.Properties.VariableNames);
%
% See also
% app_interf_descriure_dades


% START FUNCTION


% _Obtain the read_
fid = fopen(txt_data_name);
S_textscan = textscan(fid, write_values, 'Delimiter', separador_char); % Elapsed time is 0.000535 seconds.
fclose(fid);

% _Let's look at the number of elements_
% according to the input code
[~, matches_split] = strsplit(write_values, "%");
num_col = numel(matches_split);

% disp("Num columnes read_data")
% num_col

% Convert to table
if num_col == 1
    S_textscan_table = table(string(S_textscan{1}), ...
                            'VariableNames', variable_names);
elseif num_col == 2
    S_textscan_table = table(string(S_textscan{1}), ...
                              string(S_textscan{2}), ...
                            'VariableNames', variable_names);
elseif num_col == 3
    S_textscan_table = table(string(S_textscan{1}), ...
                              string(S_textscan{2}), ...
                              string(S_textscan{3}), ...
                            'VariableNames', variable_names);
elseif num_col == 4
    S_textscan_table = table(string(S_textscan{1}), ...
                              string(S_textscan{2}), ...
                              string(S_textscan{3}), ...
                              string(S_textscan{4}), ...
                            'VariableNames', variable_names);
elseif num_col == 5
    S_textscan_table = table(string(S_textscan{1}), ...
                              string(S_textscan{2}), ...
                              string(S_textscan{3}), ...
                              string(S_textscan{4}), ...
                              string(S_textscan{5}), ...
                            'VariableNames', variable_names);
elseif num_col == 6
    S_textscan_table = table(string(S_textscan{1}), ...
                              string(S_textscan{2}), ...
                              string(S_textscan{3}), ...
                              string(S_textscan{4}), ...
                              string(S_textscan{5}), ...
                              string(S_textscan{6}), ...
                            'VariableNames', variable_names);
elseif num_col == 7
    S_textscan_table = table(string(S_textscan{1}), ...
                              string(S_textscan{2}), ...
                              string(S_textscan{3}), ...
                              string(S_textscan{4}), ...
                              string(S_textscan{5}), ...
                              string(S_textscan{6}), ...
                              string(S_textscan{7}), ...
                            'VariableNames', variable_names);
elseif num_col == 8
    S_textscan_table = table(string(S_textscan{1}), ...
                              string(S_textscan{2}), ...
                              string(S_textscan{3}), ...
                              string(S_textscan{4}), ...
                              string(S_textscan{5}), ...
                              string(S_textscan{6}), ...
                              string(S_textscan{7}), ...
                              string(S_textscan{8}), ...
                            'VariableNames', variable_names);
elseif num_col == 9
    S_textscan_table = table(string(S_textscan{1}), ...
                              string(S_textscan{2}), ...
                              string(S_textscan{3}), ...
                              string(S_textscan{4}), ...
                              string(S_textscan{5}), ...
                              string(S_textscan{6}), ...
                              string(S_textscan{7}), ...
                              string(S_textscan{8}), ...
                              string(S_textscan{9}), ...                              
                            'VariableNames', variable_names);
elseif num_col == 10
    S_textscan_table = table(string(S_textscan{1}), ...
                              string(S_textscan{2}), ...
                              string(S_textscan{3}), ...
                              string(S_textscan{4}), ...
                              string(S_textscan{5}), ...
                              string(S_textscan{6}), ...
                              string(S_textscan{7}), ...
                              string(S_textscan{8}), ...
                              string(S_textscan{9}), ...
                              string(S_textscan{10}), ...                              
                            'VariableNames', variable_names);

elseif num_col == 11
S_textscan_table = table(string(S_textscan{1}), ...
                          string(S_textscan{2}), ...
                          string(S_textscan{3}), ...
                          string(S_textscan{4}), ...
                          string(S_textscan{5}), ...
                          string(S_textscan{6}), ...
                          string(S_textscan{7}), ...
                          string(S_textscan{8}), ...
                          string(S_textscan{9}), ...
                          string(S_textscan{10}), ...    
                          string(S_textscan{11}), ...                              
                        'VariableNames', variable_names);

elseif num_col == 12
S_textscan_table = table(string(S_textscan{1}), ...
                          string(S_textscan{2}), ...
                          string(S_textscan{3}), ...
                          string(S_textscan{4}), ...
                          string(S_textscan{5}), ...
                          string(S_textscan{6}), ...
                          string(S_textscan{7}), ...
                          string(S_textscan{8}), ...
                          string(S_textscan{9}), ...
                          string(S_textscan{10}), ...    
                          string(S_textscan{11}), ...                              
                          string(S_textscan{12}), ...                                                        
                        'VariableNames', variable_names);

elseif num_col == 13
S_textscan_table = table(string(S_textscan{1}), ...
                          string(S_textscan{2}), ...
                          string(S_textscan{3}), ...
                          string(S_textscan{4}), ...
                          string(S_textscan{5}), ...
                          string(S_textscan{6}), ...
                          string(S_textscan{7}), ...
                          string(S_textscan{8}), ...
                          string(S_textscan{9}), ...
                          string(S_textscan{10}), ...    
                          string(S_textscan{11}), ...                              
                          string(S_textscan{12}), ...          
                          string(S_textscan{13}), ...                                    
                        'VariableNames', variable_names);

elseif num_col == 14
S_textscan_table = table(string(S_textscan{1}), ...
                          string(S_textscan{2}), ...
                          string(S_textscan{3}), ...
                          string(S_textscan{4}), ...
                          string(S_textscan{5}), ...
                          string(S_textscan{6}), ...
                          string(S_textscan{7}), ...
                          string(S_textscan{8}), ...
                          string(S_textscan{9}), ...
                          string(S_textscan{10}), ...    
                          string(S_textscan{11}), ...                              
                          string(S_textscan{12}), ...          
                          string(S_textscan{13}), ...                                    
                          string(S_textscan{14}), ...                                                              
                        'VariableNames', variable_names);

elseif num_col == 15
S_textscan_table = table(string(S_textscan{1}), ...
                          string(S_textscan{2}), ...
                          string(S_textscan{3}), ...
                          string(S_textscan{4}), ...
                          string(S_textscan{5}), ...
                          string(S_textscan{6}), ...
                          string(S_textscan{7}), ...
                          string(S_textscan{8}), ...
                          string(S_textscan{9}), ...
                          string(S_textscan{10}), ...    
                          string(S_textscan{11}), ...                              
                          string(S_textscan{12}), ...          
                          string(S_textscan{13}), ...                                    
                          string(S_textscan{14}), ...                                    
                          string(S_textscan{15}), ...                                                             
                        'VariableNames', variable_names);

elseif num_col == 16
S_textscan_table = table(string(S_textscan{1}), ...
                          string(S_textscan{2}), ...
                          string(S_textscan{3}), ...
                          string(S_textscan{4}), ...
                          string(S_textscan{5}), ...
                          string(S_textscan{6}), ...
                          string(S_textscan{7}), ...
                          string(S_textscan{8}), ...
                          string(S_textscan{9}), ...
                          string(S_textscan{10}), ...    
                          string(S_textscan{11}), ...                              
                          string(S_textscan{12}), ...          
                          string(S_textscan{13}), ...                                    
                          string(S_textscan{14}), ...                                    
                          string(S_textscan{15}), ...  
                          string(S_textscan{16}), ...                            
                        'VariableNames', variable_names);
elseif num_col == 17
S_textscan_table = table(string(S_textscan{1}), ...
                          string(S_textscan{2}), ...
                          string(S_textscan{3}), ...
                          string(S_textscan{4}), ...
                          string(S_textscan{5}), ...
                          string(S_textscan{6}), ...
                          string(S_textscan{7}), ...
                          string(S_textscan{8}), ...
                          string(S_textscan{9}), ...
                          string(S_textscan{10}), ...    
                          string(S_textscan{11}), ...                              
                          string(S_textscan{12}), ...          
                          string(S_textscan{13}), ...                                    
                          string(S_textscan{14}), ...                                    
                          string(S_textscan{15}), ...  
                          string(S_textscan{16}), ...                            
                          string(S_textscan{17}), ...                                                      
                        'VariableNames', variable_names);

elseif num_col == 18
S_textscan_table = table(string(S_textscan{1}), ...
                          string(S_textscan{2}), ...
                          string(S_textscan{3}), ...
                          string(S_textscan{4}), ...
                          string(S_textscan{5}), ...
                          string(S_textscan{6}), ...
                          string(S_textscan{7}), ...
                          string(S_textscan{8}), ...
                          string(S_textscan{9}), ...
                          string(S_textscan{10}), ...    
                          string(S_textscan{11}), ...                              
                          string(S_textscan{12}), ...          
                          string(S_textscan{13}), ...                                    
                          string(S_textscan{14}), ...                                    
                          string(S_textscan{15}), ...  
                          string(S_textscan{16}), ...                            
                          string(S_textscan{17}), ...       
                          string(S_textscan{18}), ...                                
                        'VariableNames', variable_names);
elseif num_col == 19
S_textscan_table = table(string(S_textscan{1}), ...
                          string(S_textscan{2}), ...
                          string(S_textscan{3}), ...
                          string(S_textscan{4}), ...
                          string(S_textscan{5}), ...
                          string(S_textscan{6}), ...
                          string(S_textscan{7}), ...
                          string(S_textscan{8}), ...
                          string(S_textscan{9}), ...
                          string(S_textscan{10}), ...    
                          string(S_textscan{11}), ...                              
                          string(S_textscan{12}), ...          
                          string(S_textscan{13}), ...                                    
                          string(S_textscan{14}), ...                                    
                          string(S_textscan{15}), ...  
                          string(S_textscan{16}), ...                            
                          string(S_textscan{17}), ...       
                          string(S_textscan{18}), ...                                
                          string(S_textscan{19}), ...                                                          
                        'VariableNames', variable_names);

elseif num_col == 20
S_textscan_table = table(string(S_textscan{1}), ...
                          string(S_textscan{2}), ...
                          string(S_textscan{3}), ...
                          string(S_textscan{4}), ...
                          string(S_textscan{5}), ...
                          string(S_textscan{6}), ...
                          string(S_textscan{7}), ...
                          string(S_textscan{8}), ...
                          string(S_textscan{9}), ...
                          string(S_textscan{10}), ...    
                          string(S_textscan{11}), ...                              
                          string(S_textscan{12}), ...          
                          string(S_textscan{13}), ...                                    
                          string(S_textscan{14}), ...                                    
                          string(S_textscan{15}), ...  
                          string(S_textscan{16}), ...                            
                          string(S_textscan{17}), ...       
                          string(S_textscan{18}), ...                                
                          string(S_textscan{19}), ...                                                          
                          string(S_textscan{20}), ...                                                                                    
                        'VariableNames', variable_names);
elseif num_col == 21
S_textscan_table = table(string(S_textscan{1}), ...
                          string(S_textscan{2}), ...
                          string(S_textscan{3}), ...
                          string(S_textscan{4}), ...
                          string(S_textscan{5}), ...
                          string(S_textscan{6}), ...
                          string(S_textscan{7}), ...
                          string(S_textscan{8}), ...
                          string(S_textscan{9}), ...
                          string(S_textscan{10}), ...    
                          string(S_textscan{11}), ...                              
                          string(S_textscan{12}), ...          
                          string(S_textscan{13}), ...                                    
                          string(S_textscan{14}), ...                                    
                          string(S_textscan{15}), ...  
                          string(S_textscan{16}), ...                            
                          string(S_textscan{17}), ...       
                          string(S_textscan{18}), ...                                
                          string(S_textscan{19}), ...                                                          
                          string(S_textscan{20}), ...     
                          string(S_textscan{21}), ...                          
                        'VariableNames', variable_names);

elseif num_col == 22
S_textscan_table = table(string(S_textscan{1}), ...
                          string(S_textscan{2}), ...
                          string(S_textscan{3}), ...
                          string(S_textscan{4}), ...
                          string(S_textscan{5}), ...
                          string(S_textscan{6}), ...
                          string(S_textscan{7}), ...
                          string(S_textscan{8}), ...
                          string(S_textscan{9}), ...
                          string(S_textscan{10}), ...    
                          string(S_textscan{11}), ...                              
                          string(S_textscan{12}), ...          
                          string(S_textscan{13}), ...                                    
                          string(S_textscan{14}), ...                                    
                          string(S_textscan{15}), ...  
                          string(S_textscan{16}), ...                            
                          string(S_textscan{17}), ...       
                          string(S_textscan{18}), ...                                
                          string(S_textscan{19}), ...                                                          
                          string(S_textscan{20}), ...     
                          string(S_textscan{21}), ...       
                          string(S_textscan{22}), ...                                 
                        'VariableNames', variable_names);

elseif num_col == 23
S_textscan_table = table(string(S_textscan{1}), ...
                          string(S_textscan{2}), ...
                          string(S_textscan{3}), ...
                          string(S_textscan{4}), ...
                          string(S_textscan{5}), ...
                          string(S_textscan{6}), ...
                          string(S_textscan{7}), ...
                          string(S_textscan{8}), ...
                          string(S_textscan{9}), ...
                          string(S_textscan{10}), ...    
                          string(S_textscan{11}), ...                              
                          string(S_textscan{12}), ...          
                          string(S_textscan{13}), ...                                    
                          string(S_textscan{14}), ...                                    
                          string(S_textscan{15}), ...  
                          string(S_textscan{16}), ...                            
                          string(S_textscan{17}), ...       
                          string(S_textscan{18}), ...                                
                          string(S_textscan{19}), ...                                                          
                          string(S_textscan{20}), ...     
                          string(S_textscan{21}), ...       
                          string(S_textscan{22}), ...    
                          string(S_textscan{23}), ...                              
                        'VariableNames', variable_names);

end


% END FUNCTION


end